### ISSUE TITLE
Step 4: Hello world Projects

### ISSUE THREAD

**Issue by kevinmccartney** [kevinmccartney/we-the-party#5]
# User Stories
AS a WTP engineer
I WANT TO see a "Hello, world" for the applications & infrastructure 
SO THAT I know the starting point is working

AS a WTP engineer
I WANT TO be able to use a wtp cli to generate VS code workspace configuration
SO THAT I can leverage my IDE features for a better dev experience

# Functional Requirements
* Add "Hello, world" for app/infrastrucure
  * wtp_admin
  * wtp_admin_api
  * wtp_api
  * wtp_infra
  * wtp_party
* Add Hello, World tests where possible 
* Create `wtp` cli with 
  * `config generate vscode` command
    * This command also accepts the --type=minimal|recommended|opinionated flag to determine settings
  * `start aws-lambda` command
* Set up language version constraints
  * [Terraform](https://learn.hashicorp.com/tutorials/terraform/versions?in=terraform/1-0)
  * [Pyenv](https://github.com/pyenv/pyenv#switch-between-python-versions)
  * [NVM](https://github.com/nvm-sh/nvm#nvmrc)
    * Look into shell integration
  * [npm engines](https://stackoverflow.com/a/29349773)
    * [prevent yarn usage](https://www.freecodecamp.org/news/how-to-force-use-yarn-or-npm/) 

# Notes
- You may need to set interpreters for python language features, black, pylint, etc

**Comment by kevinmccartney** [comment]
# TODO:
  - [x] Add body to post
  - [x] Cli config generation
  - [x] Flesh out cli decorator args
  - [x] Shorthand cli flags
  - [x] Use directory param
  - [x] Add outfile flag
  - [x] Make file not found decorator
  - [x] Verbose mode
  - [x] Debug python tests
  - [x] Bandit
  - [x] Central logger
  - [x] Add colors to cli
  - [x] Typing & other suggestions
  - [x] Look up Black configuration
  - [x] Look into linters
  - [ ] Fix lint errors
  - [ ] Add err codes
  - [ ] PyUpgrade
  - [ ] docformatter
  - [ ] Refactor
  - [ ] Shell completions
  - [ ] Add wizard where appropriate
  - [ ] Top level error handler
  - [ ] Document PID debugging deferral
  - [ ] Add dependency graphs for docs
  - [ ] Add support for generating workspace configs with less than all workspaces
  - [ ] Document click shortcomings
  - [ ] Add workspace to gitignore
  - [ ] Tests for cli
  - [ ] Hello world tf
  - [ ] Language constraints
  - [ ] Add launch configs for attaching python debugger
  - [ ] Add npm scripts for debugging tests https://create-react-app.dev/docs/debugging-tests/
  - [ ] docs on how to run projects
  - [ ] Set up python tests in VS Code
  - [ ] Look into CodeQL
  - [ ] Integrate symilar
